### ISSUE TITLE
可以添加下默认的Query和Mutation 么

### ISSUE THREAD

**Issue by ypli0629** [Carrotzpc/egg-graphql#5]

**Comment by Carrotzpc** [comment]
能简单描述下需要添加默认的 Query 和 Mutation 的使用场景吗？

**Comment by ypli0629** [comment]
主要还是为了组织目录使用，可以通过 extend 将 Query 定义到每个 graphql 模型中去，现在只能定义到公共的 graphql 中

**Comment by Carrotzpc** [comment]
已支持，为兼容老版本，添加定义默认是关闭的，可以通过设置 `defaultTypeDefsEnabled` 为 `true` 开启，可以安装最新版试下 @ypli0629

**Comment by ypli0629** [comment]
good，测试可以
